CREATE DATABASE "Data warehouse"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
	
CREATE SCHEMA IF NOT EXISTS bronze
    AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS silver
    AUTHORIZATION postgres;
CREATE SCHEMA IF NOT EXISTS gold
    AUTHORIZATION postgres;

